/**
 * Vector Nodes Module Export
 * Includes both basic and extended vector operations (36 total nodes)
 */

export {
  // Basic Node Classes (6)
  VectorMathNode,
  VectorRotateNode,
  CombineXYZNode,
  SeparateXYZNode,
  NormalizeNode,
  MappingNode,
  
  // Extended Node Classes (30)
  VectorTransformNode,
  NormalMapNode,
  BumpNode,
  DisplacementNode,
  AlignEulerToVectorNode,
  RotateEulerNode,
  QuaternionNode,
  MatrixTransformNode,
  DirectionToPointNode,
  ReflectNode,
  RefractNode,
  FaceForwardNode,
  WrapNode,
  SnapNode,
  FloorCeilNode,
  ModuloNode,
  FractionNode,
  AbsoluteNode,
  MinMaxNode,
  TrigonometryNode,
  PowerLogNode,
  SignNode,
  CompareNode,
  SmoothMinMaxNode,
  AngleBetweenNode,
  SlerpNode,
  PolarToCartNode,
  CartToPolarNode,
  
  // Type Definitions (Basic)
  type VectorNodeBase,
  type VectorMathInputs,
  type VectorMathOutputs,
  type VectorRotateInputs,
  type VectorRotateOutputs,
  type MappingInputs,
  type MappingOutputs,
  type CombineXYZInputs,
  type CombineXYZOutputs,
  type SeparateXYZInputs,
  type SeparateXYZOutputs,
  type NormalizeInputs,
  type NormalizeOutputs,
  
  // Type Definitions (Extended)
  type VectorTransformInputs,
  type VectorTransformOutputs,
  type NormalMapInputs,
  type NormalMapOutputs,
  type BumpInputs,
  type BumpOutputs,
  type DisplacementInputs,
  type DisplacementOutputs,
  type AlignEulerToVectorInputs,
  type AlignEulerToVectorOutputs,
  type RotateEulerInputs,
  type RotateEulerOutputs,
  type QuaternionInputs,
  type QuaternionOutputs,
  type MatrixTransformInputs,
  type MatrixTransformOutputs,
  type DirectionToPointInputs,
  type DirectionToPointOutputs,
  type ReflectInputs,
  type ReflectOutputs,
  type RefractInputs,
  type RefractOutputs,
  type FaceForwardInputs,
  type FaceForwardOutputs,
  type WrapInputs,
  type WrapOutputs,
  type SnapInputs,
  type SnapOutputs,
  type FloorCeilInputs,
  type FloorCeilOutputs,
  type ModuloInputs,
  type ModuloOutputs,
  type FractionInputs,
  type FractionOutputs,
  type AbsoluteInputs,
  type AbsoluteOutputs,
  type MinMaxInputs,
  type MinMaxOutputs,
  type TrigonometryInputs,
  type TrigonometryOutputs,
  type PowerLogInputs,
  type PowerLogOutputs,
  type SignInputs,
  type SignOutputs,
  type CompareInputs,
  type CompareOutputs,
  type SmoothMinMaxInputs,
  type SmoothMinMaxOutputs,
  type AngleBetweenInputs,
  type AngleBetweenOutputs,
  type SlerpInputs,
  type SlerpOutputs,
  type PolarToCartInputs,
  type PolarToCartOutputs,
  type CartToPolarInputs,
  type CartToPolarOutputs,
  
  // Factory Functions (Basic)
  createVectorMathNode,
  createVectorRotateNode,
  createCombineXYZNode,
  createSeparateXYZNode,
  createNormalizeNode,
  createMappingNode,
} from './VectorNodes';

// Re-export extended nodes
export {
  VectorTransformNode,
  NormalMapNode,
  BumpNode,
  DisplacementNode,
  AlignEulerToVectorNode,
  RotateEulerNode,
  QuaternionNode,
  MatrixTransformNode,
  DirectionToPointNode,
  ReflectNode,
  RefractNode,
  FaceForwardNode,
  WrapNode,
  SnapNode,
  FloorCeilNode,
  ModuloNode,
  FractionNode,
  AbsoluteNode,
  MinMaxNode,
  TrigonometryNode,
  PowerLogNode,
  SignNode,
  CompareNode,
  SmoothMinMaxNode,
  AngleBetweenNode,
  SlerpNode,
  PolarToCartNode,
  CartToPolarNode,
} from './VectorNodesExtended';
