/**
 * ShaderIncludes — Unified GLSL shader include system
 *
 * Provides namespace-prefixed GLSL functions to eliminate the 3-6x duplication
 * of noise/PBR functions across:
 * - GLSLProceduralTexturePipeline.ts
 * - RuntimeMaterialBuilder.ts
 * - TriplanarProjection.ts
 * - SDFPerturbSurface.ts
 * - PerInstanceMaterialRandomization.ts
 *
 * Each function takes a `prefix` parameter that namespaces all GLSL function
 * names, avoiding collisions when multiple modules include the same library.
 *
 * Example usage:
 * ```typescript
 * const noiseGLSL = ShaderIncludes.getNoiseGLSL('terrain');
 * // Produces: terrain_snoise3D, terrain_perlin3D, terrain_fbm3D, etc.
 *
 * const pbrGLSL = ShaderIncludes.getPBRGLSL('mat');
 * // Produces: mat_fresnelSchlick, mat_distributionGGX, etc.
 * ```
 *
 * @module assets/shaders/common
 */

import {
  SIMPLEX_3D_GLSL,
  SIMPLEX_2D_GLSL,
  PERLIN_3D_GLSL,
  FBM_GLSL,
  MUSGRAVE_GLSL,
  DOMAIN_WARP_GLSL,
  HSV_RGB_GLSL,
  VALUE_NOISE_GLSL,
} from './NoiseGLSL';
import { PBR_GLSL } from './PBRGLSL';
import {
  VORONOI_2D_GLSL,
  VORONOI_3D_GLSL,
  VORONOI_EDGE_GLSL,
} from './VoronoiGLSL';

// ============================================================================
// ShaderIncludes
// ============================================================================

export class ShaderIncludes {
  /**
   * Get namespaced noise GLSL functions.
   *
   * Wraps the canonical noise implementations from NoiseGLSL.ts with
   * a namespace prefix to avoid collisions with other modules that
   * define their own noise functions.
   *
   * @param prefix - Namespace prefix (e.g., 'terrain', 'bark', 'rock')
   * @returns GLSL string with prefixed function names
   */
  static getNoiseGLSL(prefix: string): string {
    // Build namespaced versions of core noise functions
    return /* glsl */ `
// ============================================================================
// Namespaced Noise Functions: ${prefix}_
// Auto-generated by ShaderIncludes
// ============================================================================

// --- 3D Simplex Noise (${prefix}) ---
${ShaderIncludes.prefixGLSL(SIMPLEX_3D_GLSL, prefix, [
  'mod289_v3', 'mod289_v4', 'permute_v4', 'taylorInvSqrt_v4', 'snoise3D',
])}

// --- 2D Simplex Noise (${prefix}) ---
${ShaderIncludes.prefixGLSL(SIMPLEX_2D_GLSL, prefix, [
  'mod289_2d_v3', 'mod289_2d_v2', 'permute_2d_v3', 'snoise2D',
])}

// --- 3D Perlin Noise (${prefix}) ---
${ShaderIncludes.prefixGLSL(PERLIN_3D_GLSL, prefix, [
  'hash33_grad', 'perlin3D',
])}

// --- FBM (${prefix}) ---
${ShaderIncludes.prefixGLSL(FBM_GLSL, prefix, [
  'fbm3D', 'fbm2D',
])}

// --- Musgrave Variants (${prefix}) ---
${ShaderIncludes.prefixGLSL(MUSGRAVE_GLSL, prefix, [
  'musgraveFBM', 'musgraveRidged', 'musgraveHeteroTerrain', 'musgraveMultiFractal',
])}

// --- Domain Warp (${prefix}) ---
${ShaderIncludes.prefixGLSL(DOMAIN_WARP_GLSL, prefix, [
  'domainWarp', 'domainWarpDouble',
])}

// --- HSV/RGB (${prefix}) ---
${ShaderIncludes.prefixGLSL(HSV_RGB_GLSL, prefix, [
  'hsv2rgb', 'rgb2hsv',
])}

// --- Value Noise (${prefix}) ---
${ShaderIncludes.prefixGLSL(VALUE_NOISE_GLSL, prefix, [
  'hash3D', 'valueNoise3D', 'hash2D', 'valueNoise2D',
])}
`;
  }

  /**
   * Get namespaced 4D noise GLSL functions.
   *
   * Includes 4D simplex, 4D perlin, and 4D FBM variants.
   *
   * @param prefix - Namespace prefix
   * @returns GLSL string with 4D noise functions
   */
  static getNoise4DGLSL(prefix: string): string {
    return /* glsl */ `
// ============================================================================
// 4D Noise Functions: ${prefix}_
// ============================================================================

// 4D hash for gradient noise
vec4 ${prefix}_mod289_v4_4d(vec4 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
vec3 ${prefix}_mod289_v3_4d(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
vec4 ${prefix}_permute_v4_4d(vec4 x) { return ${prefix}_mod289_v4_4d(((x * 34.0) + 10.0) * x); }
vec4 ${prefix}_taylorInvSqrt_v4_4d(vec4 r) { return 1.79284291400159 - 0.85373472095314 * r; }

// 4D Simplex Noise
float ${prefix}_snoise4D(vec4 v) {
  const vec2 C = vec2(0.1381966011250105, 0.3090169943749475);
  const vec4 D = vec4(1.0, 1.0, 1.0, -1.0);

  vec3 i = floor(v.xyz + dot(v.xyz, C.yyy));
  vec3 x0 = v.xyz - i + dot(i, C.xxx);

  vec3 g = step(x0.yzx, x0.xyz);
  vec3 l = 1.0 - g;
  vec3 i1 = min(g.xyz, l.zxy);
  vec3 i2 = max(g.xyz, l.zxy);

  vec3 x1 = x0 - i1 + C.xxx;
  vec3 x2 = x0 - i2 + C.yyy;
  vec3 x3 = x0 - D.yyy;

  // Permutations
  i = ${prefix}_mod289_v3_4d(i);
  float w = v.w;
  vec4 p = ${prefix}_permute_v4_4d(${prefix}_permute_v4_4d(${prefix}_permute_v4_4d(
    i.z + vec4(0.0, i1.z, i2.z, 1.0))
    + i.y + vec4(0.0, i1.y, i2.y, 1.0))
    + i.x + vec4(0.0, i1.x, i2.x, 1.0));

  // Add W dimension offset
  p = ${prefix}_permute_v4_4d(p + vec4(w));

  float n_ = 0.142857142857;
  vec3 ns = n_ * D.wyz - D.xzx;

  vec4 j = p - 49.0 * floor(p * ns.z * ns.z);

  vec4 x_ = floor(j * ns.z);
  vec4 y_ = floor(j - 7.0 * x_);

  vec4 x = x_ * ns.x + ns.yyyy;
  vec4 y = y_ * ns.x + ns.yyyy;
  vec4 h = 1.0 - abs(x) - abs(y);

  vec4 b0 = vec4(x.xy, y.xy);
  vec4 b1 = vec4(x.zw, y.zw);

  vec4 s0 = floor(b0) * 2.0 + 1.0;
  vec4 s1 = floor(b1) * 2.0 + 1.0;
  vec4 sh = -step(h, vec4(0.0));

  vec4 a0 = b0.xzyw + s0.xzyw * sh.xxyy;
  vec4 a1 = b1.xzyw + s1.xzyw * sh.zzww;

  vec3 p0 = vec3(a0.xy, h.x);
  vec3 p1 = vec3(a0.zw, h.y);
  vec3 p2 = vec3(a1.xy, h.z);
  vec3 p3 = vec3(a1.zw, h.w);

  vec4 norm = ${prefix}_taylorInvSqrt_v4_4d(vec4(dot(p0, p0), dot(p1, p1), dot(p2, p2), dot(p3, p3)));
  p0 *= norm.x;
  p1 *= norm.y;
  p2 *= norm.z;
  p3 *= norm.w;

  vec4 m = max(0.5 - vec4(dot(x0, x0), dot(x1, x1), dot(x2, x2), dot(x3, x3)), 0.0);
  m = m * m;
  return 105.0 * dot(m * m, vec4(dot(p0, x0), dot(p1, x1), dot(p2, x2), dot(p3, x3)));
}

// 4D Perlin gradient noise
vec3 ${prefix}_hash33_4d(vec3 p, float w) {
  p = vec3(dot(p, vec3(127.1, 311.7, 74.7)) + w * 13.0,
           dot(p, vec3(269.5, 183.3, 246.1)) + w * 7.3,
           dot(p, vec3(113.5, 271.9, 124.6)) + w * 3.1);
  return -1.0 + 2.0 * fract(sin(p) * 43758.5453123);
}

float ${prefix}_perlin4D(vec3 p, float w) {
  vec3 i = floor(p);
  vec3 f = fract(p);
  vec3 u = f * f * (3.0 - 2.0 * f);

  return mix(mix(mix(dot(${prefix}_hash33_4d(i + vec3(0,0,0), w), f - vec3(0,0,0)),
                     dot(${prefix}_hash33_4d(i + vec3(1,0,0), w), f - vec3(1,0,0)), u.x),
                 mix(dot(${prefix}_hash33_4d(i + vec3(0,1,0), w), f - vec3(0,1,0)),
                     dot(${prefix}_hash33_4d(i + vec3(1,1,0), w), f - vec3(1,1,0)), u.x), u.y),
             mix(mix(dot(${prefix}_hash33_4d(i + vec3(0,0,1), w), f - vec3(0,0,1)),
                     dot(${prefix}_hash33_4d(i + vec3(1,0,1), w), f - vec3(1,0,1)), u.x),
                 mix(dot(${prefix}_hash33_4d(i + vec3(0,1,1), w), f - vec3(0,1,1)),
                     dot(${prefix}_hash33_4d(i + vec3(1,1,1), w), f - vec3(1,1,1)), u.x), u.y), u.z);
}

// 4D FBM (3D position + W seed dimension)
float ${prefix}_fbm4D(vec3 p, float w, int octaves, float lacunarity, float gain) {
  float value = 0.0;
  float amplitude = 1.0;
  float frequency = 1.0;
  float maxValue = 0.0;
  float wOffset = w;

  for (int i = 0; i < 16; i++) {
    if (i >= octaves) break;
    value += amplitude * ${prefix}_snoise4D(vec4(p * frequency, wOffset));
    maxValue += amplitude;
    amplitude *= gain;
    frequency *= lacunarity;
    wOffset += 17.0; // Offset W per octave for variation
  }

  return value / max(maxValue, 0.001);
}

// 4D Musgrave FBM
float ${prefix}_musgraveFBM4D(vec3 p, float w, float scale, int octaves, float dimension, float lacunarity) {
  float gain = pow(0.5, 2.0 - dimension);
  return ${prefix}_fbm4D(p * scale, w, octaves, lacunarity, gain);
}

// 4D Musgrave Ridged
float ${prefix}_musgraveRidged4D(vec3 p, float w, float scale, int octaves, float dimension, float lacunarity, float offset, float gain) {
  float value = 0.0;
  float amplitude = 1.0;
  float frequency = 1.0;
  float maxValue = 0.0;
  float weight = 1.0;
  float wOffset = w;

  for (int i = 0; i < 16; i++) {
    if (i >= octaves) break;
    float signal = ${prefix}_snoise4D(vec4(p * scale * frequency, wOffset));
    signal = abs(signal);
    signal = offset - signal;
    signal *= signal;
    signal *= weight;
    weight = clamp(signal * gain, 0.0, 1.0);
    value += signal * amplitude;
    maxValue += amplitude;
    amplitude *= pow(lacunarity, -dimension);
    frequency *= lacunarity;
    wOffset += 17.0;
  }

  return value / max(maxValue, 0.001);
}

// 4D Musgrave HeteroTerrain
float ${prefix}_musgraveHetero4D(vec3 p, float w, float scale, int octaves, float dimension, float lacunarity, float offset) {
  float gain = pow(0.5, 2.0 - dimension);
  float value = offset + ${prefix}_snoise4D(vec4(p * scale, w));
  float amplitude = 1.0;
  float frequency = 1.0;
  float maxValue = 1.0;
  float wOffset = w + 31.0;

  for (int i = 1; i < 16; i++) {
    if (i >= octaves) break;
    amplitude *= gain;
    frequency *= lacunarity;
    float signal = (${prefix}_snoise4D(vec4(p * scale * frequency, wOffset)) + offset) * amplitude;
    value += signal;
    maxValue += amplitude;
    wOffset += 17.0;
  }

  return value / max(maxValue, 0.001);
}
`;
  }

  /**
   * Get namespaced PBR lighting GLSL functions.
   *
   * @param prefix - Namespace prefix
   * @returns GLSL string with prefixed PBR functions
   */
  static getPBRGLSL(prefix: string): string {
    return /* glsl */ `
// ============================================================================
// Namespaced PBR Functions: ${prefix}_
// ============================================================================

${ShaderIncludes.prefixGLSL(PBR_GLSL, prefix, [
  'fresnelSchlick', 'fresnelSchlickRoughness', 'distributionGGX',
  'geometrySchlickGGX', 'geometrySmith', 'computePBRLight',
  'distributionGGXAniso', 'geometrySmithAniso', 'computeAnisoPBRLight',
])}
`;
  }

  /**
   * Get namespaced Voronoi GLSL functions.
   *
   * @param prefix - Namespace prefix
   * @returns GLSL string with prefixed Voronoi functions
   */
  static getVoronoiGLSL(prefix: string): string {
    return /* glsl */ `
// ============================================================================
// Namespaced Voronoi Functions: ${prefix}_
// ============================================================================

${ShaderIncludes.prefixGLSL(VORONOI_2D_GLSL, prefix, [
  'hash22_voronoi2d', 'voronoi2D',
  // Also prefix struct name
])}

${ShaderIncludes.prefixGLSL(VORONOI_3D_GLSL, prefix, [
  'hash33_voronoi3d', 'voronoi3D',
])}

${ShaderIncludes.prefixGLSL(VORONOI_EDGE_GLSL, prefix, [
  'voronoiEdge2D',
])}
`;
  }

  /**
   * Get a combined noise + PBR + Voronoi include with a single prefix.
   *
   * @param prefix - Namespace prefix
   * @param include4D - Whether to include 4D noise variants (default: true)
   * @returns Combined GLSL string
   */
  static getFullInclude(prefix: string, include4D: boolean = true): string {
    let glsl = ShaderIncludes.getNoiseGLSL(prefix);
    if (include4D) {
      glsl += ShaderIncludes.getNoise4DGLSL(prefix);
    }
    glsl += ShaderIncludes.getPBRGLSL(prefix);
    glsl += ShaderIncludes.getVoronoiGLSL(prefix);
    return glsl;
  }

  // ===========================================================================
  // Internal: GLSL Prefix Rewriting
  // ===========================================================================

  /**
   * Prefix all function names in a GLSL string with a namespace prefix.
   *
   * For each function name in the `functions` list, this replaces:
   * - Function definitions: `float name(` → `float ${prefix}_name(`
   * - Function calls: `name(` → `${prefix}_name(`
   *
   * Struct names are also prefixed by convention.
   *
   * @param glsl - The GLSL source string
   * @param prefix - The namespace prefix
   * @param functions - List of function/struct names to prefix
   * @returns Prefixed GLSL string
   */
  private static prefixGLSL(glsl: string, prefix: string, functions: string[]): string {
    let result = glsl;

    for (const fn of functions) {
      // Use a regex to replace function names but not inside comments or strings
      // Pattern: word boundary + function name + word boundary or (
      const escaped = fn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      // Replace function definitions and calls, but not in comments
      const regex = new RegExp(`\\b${escaped}\\b(?=\\s*\\()`, 'g');
      result = result.replace(regex, `${prefix}_${fn}`);
    }

    // Also prefix struct names (e.g., VoronoiResult2D → prefix_VoronoiResult2D)
    const structPattern = /struct\s+(\w+)\s*\{/g;
    let match;
    while ((match = structPattern.exec(result)) !== null) {
      const structName = match[1];
      if (!structName.startsWith(`${prefix}_`)) {
        // Replace struct name definition and all usages
        const structRegex = new RegExp(`\\b${structName}\\b`, 'g');
        result = result.replace(structRegex, `${prefix}_${structName}`);
      }
    }

    return result;
  }
}
